# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Crear Version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:
    inputs:
      Branch:
        description: 'Nombre de la rama de mantenimiento para la release que se va a generar (Ejemplo: "1.0.X", si se va a generar la release 1.0.0).'
        default: '.X'
        required: true
      Trunk:
        description: 'Versión a la que actualizar el trunk (Ejemplo: "1.1.0-SNAPSHOT", si se va a generar la release 1.0.0).'
        default: '-SNAPSHOT'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn release:branch -DdevelopmentVersion=${{github.event.inputs.Trunk}} -DreleaseVersion=${{github.event.inputs.Branch}}
